SimplyAdmire:
  Facets:
    service:
      importService:
        options:
         defaultReferenceNodePath: '/sites/facets/content-elements'
         defaultContentCollectionNodePath: 'main'
        data:
         documents: 'resource://SimplyAdmire.Facets/Private/Content/Sites.xml'
         nodeTypes:
          text: 'resource://SimplyAdmire.Facets/Private/Content/NodeTypes/Text.xml'
          textWithImage: 'resource://SimplyAdmire.Facets/Private/Content/NodeTypes/TextWithImage.xml'
